DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS post;

CREATE TABLE usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome_usuario TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  autor_id INTEGER NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  titulo TEXT NOT NULL,
  corpo TEXT NOT NULL,
  FOREIGN KEY (autor_id) REFERENCES user (id)
);